services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: location
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"